version = 0.1
[default.global.parameters]
stack_name = "aws-image-generation"
[default]
[default.deploy]
[default.deploy.parameters]
s3_bucket = "image-generation-default-samclisourcebucket-mtmbth8ve8z"
s3_prefix = "aws-image-generation-app-prefix"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
