AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Ambry Image Generation Service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 300
    Environment:
      Variables:
        AVI_URL: !Ref aviUrlValue
        AVI_TIMEOUT: !Ref aviAxiosTimeout

Parameters:
  aviUrlValue:
    Type: String
  aviAxiosTimeout:
    Type: Number
    Default: 10000

Resources:
  BayesDelImageGenerationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/handlers
      Handler: bayesdel.handler
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /images/bayesdel/{alteration}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ImageGenerationApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/images/bayesdel/{alteration}"
  BayesDelImageGenerationFunction:
    Description: "Bayesdel Image Generation ARN"
    Value: !GetAtt BayesDelImageGenerationFunction.Arn
  ImageGeneratioIamRole:
    Description: "Implicit IAM Role created for Image Generation function"
    Value: !GetAtt BayesDelImageGenerationFunction.Arn
